# Generated by Django 4.2.5 on 2023-09-23 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raspisanie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pair',
            name='seat_number',
            field=models.IntegerField(default=0, verbose_name='Количество мест'),
            preserve_default=False,
        ),
    ]
